### ISSUE TITLE
IndexOutOfBoundsException when trying to move

### ISSUE THREAD

**Issue by muuknl** [storm345dev/ucars#3]
I love this api/plugin, and I have had no issues with it up until now. When I try to move inside a cart, it spits out an IndexOutOfBoundsException:
```
[15:26:26 WARN]: [uCars] Task #23922 for uCars v19 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.7.0_67]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.7.0_67]
        at java.util.Collections$UnmodifiableList.get(Unknown Source) ~[?:1.7.0_67]
        at com.useful.ucars.ControlInput.getAccel(ControlInput.java:23) ~[?:?]
        at com.useful.ucars.ControlInput.input(ControlInput.java:38) ~[?:?]
        at com.useful.ucars.MotionManager$1.run(MotionManager.java:127) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-2f787bd-501372f]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
```

**Comment by storm345** [comment]
Will fix this asap! Please create a ticket on the bukkit page if you havent already else I may forget : p
